services:
  # PostgreSQL Veritabanı Servisi
  db:
    image: postgres:16-alpine
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Backend Servisi (Servis Adı: app)
  app:
    build:
      context: ./backend
    container_name: backend_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Nginx Web Sunucusu ve Reverse Proxy Servisi
  web:
    build:
      context: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      # Nginx Konfigürasyonu için Volume Bağlantısı
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Frontend Statik Dosyaları için Volume Bağlantısı
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app

volumes:
  postgres_data:
